### ISSUE TITLE
LongType Column insertion fails if CommitLog is enabled

### ISSUE THREAD

**Issue by marsred** [hmsonline/cassandra-triggers#51]
I have a column family with Comparator as LongType. When I set the CommitLog as enabled in the Configuration CF and try to insert any data in the LongType column, it fails with the following error:

ERROR 11:10:05,483 Error occurred during processing of message.
    java.nio.charset.MalformedInputException: Input length = 1
        at java.nio.charset.CoderResult.throwException(CoderResult.java:277)
    at java.nio.charset.CharsetDecoder.decode(CharsetDecoder.java:798)
    at org.apache.cassandra.utils.ByteBufferUtil.string(ByteBufferUtil.java:163)
    at org.apache.cassandra.utils.ByteBufferUtil.string(ByteBufferUtil.java:120)
    at com.hmsonline.cassandra.triggers.dao.CommitLog.writePending(CommitLog.java:57)
    at com.hmsonline.cassandra.triggers.CassandraServerTriggerAspect.writePending(CassandraServerTriggerAspect.java:72)
    at com.hmsonline.cassandra.triggers.CassandraServerTriggerAspect.ajc$inlineAccessMethod$com_hmsonline_cassandra_triggers_CassandraServerTriggerAspect$com_hmsonline_cassandra_triggers_CassandraServerTriggerAspect$writePending(CassandraServerTriggerAspect.java:1)
    at com.hmsonline.cassandra.triggers.CassandraServerTriggerAspect.writeToCommitLog(CassandraServerTriggerAspect.java:34)
    at org.apache.cassandra.thrift.CassandraServer.doInsert(CassandraServer.java:629)
    at org.apache.cassandra.thrift.CassandraServer.internal_batch_mutate(CassandraServer.java:587)
    at org.apache.cassandra.thrift.CassandraServer.batch_mutate(CassandraServer.java:595)
    at org.apache.cassandra.thrift.Cassandra$Processor$batch_mutate.getResult(Cassandra.java:3112)
    at org.apache.cassandra.thrift.Cassandra$Processor$batch_mutate.getResult(Cassandra.java:3100)
    at org.apache.thrift.ProcessFunction.process(ProcessFunction.java:32)
    at org.apache.thrift.TBaseProcessor.process(TBaseProcessor.java:34)
    at org.apache.cassandra.thrift.CustomTThreadPoolServer$WorkerProcess.run(CustomTThreadPoolServer.java:186)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1110)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:603)
    at java.lang.Thread.run(Thread.java:722)

Cassandra Version: 1.1.0
Trigger Version: 1.0.1

**Comment by boneill42** [comment]
Yeah, that¹s bad.

Thanks for creating an issue for this:
https://github.com/hmsonline/cassandra-triggers/issues/51

FYI, we've decreased the amount of effort we're putting towards this module
because the trigger functionality is being incorporated in Cassandra.
(hopefully 1.2)
https://issues.apache.org/jira/browse/CASSANDRA-1311

-brian

---

Brian O'Neill
Lead Architect, Software Development
Health Market Science
The Science of Better Results
2700 Horizon Drive € King of Prussia, PA € 19406
M: 215.588.6024 € @boneill42 http://www.twitter.com/boneill42   €
healthmarketscience.com

This information transmitted in this email message is for the intended
recipient only and may contain confidential and/or privileged material. If
you received this email in error and are not the intended recipient, or the
person responsible to deliver it to the intended recipient, please contact
the sender at the email above and delete this email and any attachments and
destroy any copies thereof. Any review, retransmission, dissemination,
copying or other use of, or taking any action in reliance upon, this
information by persons or entities other than the intended recipient is
strictly prohibited.

From:  ksr04 notifications@github.com
Reply-To:  hmsonline/cassandra-triggers
<reply+i-8594363-14c6363ff5a7ce252509ddcdfbeaf4cff7458a02-897229@reply.githu
b.com>
Date:  Friday, November 23, 2012 12:45 AM
To:  hmsonline/cassandra-triggers cassandra-triggers@noreply.github.com
Subject:  [cassandra-triggers] LongType Column insertion fails if CommitLog
is enabled (#51)

I have a column family with Comparator as LongType. When I set the CommitLog
as enabled in the Configuration CF and try to insert any data in the
LongType column, it fails with the following error:

ERROR 11:10:05,483 Error occurred during processing of message.
 java.nio.charset.MalformedInputException: Input length = 1
 at java.nio.charset.CoderResult.throwException(CoderResult.java:277)
 at java.nio.charset.CharsetDecoder.decode(CharsetDecoder.java:798)
 at 
org.apache.cassandra.utils.ByteBufferUtil.string(ByteBufferUtil.java:163)
 at 
org.apache.cassandra.utils.ByteBufferUtil.string(ByteBufferUtil.java:120)
 at 
com.hmsonline.cassandra.triggers.dao.CommitLog.writePending(CommitLog.java:5
7)
 at 
com.hmsonline.cassandra.triggers.CassandraServerTriggerAspect.writePending(C
assandraServerTriggerAspect.java:72)
 at 
com.hmsonline.cassandra.triggers.CassandraServerTriggerAspect.ajc$inlineAcce
ssMethod$com_hmsonline_cassandra_triggers_CassandraServerTriggerAspect$com_h
msonline_cassandra_triggers_CassandraServerTriggerAspect$writePending(Cassan
draServerTriggerAspect.java:1)
 at 
com.hmsonline.cassandra.triggers.CassandraServerTriggerAspect.writeToCommitL
og(CassandraServerTriggerAspect.java:34)
 at 
org.apache.cassandra.thrift.CassandraServer.doInsert(CassandraServer.java:62
9)
 at 
org.apache.cassandra.thrift.CassandraServer.internal_batch_mutate(CassandraS
erver.java:587)
 at 
org.apache.cassandra.thrift.CassandraServer.batch_mutate(CassandraServer.jav
a:595)
 at 
org.apache.cassandra.thrift.Cassandra$Processor$batch_mutate.getResult(Cassa
ndra.java:3112)
 at 
org.apache.cassandra.thrift.Cassandra$Processor$batch_mutate.getResult(Cassa
ndra.java:3100)
 at org.apache.thrift.ProcessFunction.process(ProcessFunction.java:32)
 at org.apache.thrift.TBaseProcessor.process(TBaseProcessor.java:34)
 at 
org.apache.cassandra.thrift.CustomTThreadPoolServer$WorkerProcess.run(Custom
TThreadPoolServer.java:186)
 at 
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:11
10)
 at 
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:6
03)
 at java.lang.Thread.run(Thread.java:722)

Cassandra Version: 1.1.0
Trigger Version: 1.0.1

 ‹
 Reply to this email directly or view it on GitHub
https://github.com/hmsonline/cassandra-triggers/issues/51 .
